[colors.bright]
black = "0x555551"
blue = "0x007FFF"
cyan = "0x00CCCC"
green = "0x03C03C"
magenta = "0xFF1493"
red = "0xFF2400"
white = "0xFFFAFA"
yellow = "0xFDFF00"

[colors.normal]
black = "0x222221"
blue = "0x0087BD"
cyan = "0x20B2AA"
green = "0x32d16e"
magenta = "0x9A4EAE"
red = "0xdf0a0a"
white = "0xC6C6C4"
yellow = "0xFFD700"

[colors.primary]
background = "0x10100E"
foreground = "0xC6C6C4"

[cursor.style]
blinking = "Always"
shape = "Block"

[env]

[font]
size = 11.0
normal = { family = "FiraCodeNerdFont", style = "Regular" }
bold = { family = "FiraCodeNerdFont", style = "Bold" }
italic = { family = "FiraCodeNerdFont", style = "Italic" }

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[window]
decorations = "none"
opacity = 1

[selection]
semantic_escape_chars = "┤├,│`|:\"' ()[]{}<>\t"
